import { PropsWithChildren } from 'react';

import { CssBaseline } from '@mui/material';
import type { Metadata } from 'next';

import userDataFetcher from '@/apis/userFetcher';
import UserDataProvider from '@/store/providers';
import AppThemeProvider from '@/theme/Provider';

import './globals.css';

export const metadata: Metadata = {
  title: 'Ebuddy Test',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }: PropsWithChildren<unknown>) => {
  const { userData } = await userDataFetcher();

  return (
    <html lang="en">
      <CssBaseline />
      <body>
        <AppThemeProvider>
          <UserDataProvider
            initialStore={{
              profile: {
                userData: userData || {},
                profileName: userData?.name || '',
              },
            }}
          >
            {children}
          </UserDataProvider>
        </AppThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
