import { PropsWithChildren } from 'react';

import { CssBaseline } from '@mui/material';
import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';

import userDataFetcher from '@/apis/userFetcher';
import UserDataProvider from '@/store/providers';

import './globals.css';

const workSans = Work_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Ebuddy Test',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }: PropsWithChildren<unknown>) => {
  const { userData } = await userDataFetcher();

  return (
    <html lang="en">
      <CssBaseline />
      <body className={workSans.className}>
        <UserDataProvider initialStore={{ userData: userData || {} }}>{children}</UserDataProvider>
      </body>
    </html>
  );
};

export default RootLayout;
